### ISSUE TITLE
Ability to ignore violations from selected directories/files

### ISSUE THREAD

**Issue by miki725** [dealertrack/flake8-diff#12]
If any auto-generated code is pushed to VCS (e.g. SQLAlchemy generated table definitions or South migrations), it will have many violations hence there should be a way to ignore those. Perhaps:

    $ flake8-diff ... --ignore-files=path/to/ignore

**Comment by jayvdb** [comment]
`--flake8-options` has been added; should this be closed?

**Comment by miki725** [comment]
yep. thanks @jayvdb for the reminder
