### ISSUE TITLE
All supported VCSs need to be installed in order to run flake8-diff

### ISSUE THREAD

**Issue by mikewaters** [dealertrack/flake8-diff#26]
If I run the flake8-diff command on a box that is missing a supported VCS, an error occurs:

    flake8-diff: error: VCS "hg" installation could not be found. Is it on $PATH?

Perhaps https://github.com/dealertrack/flake8-diff/blob/master/flake8diff/vcs/__init__.py#L9 can catch `UnsupportedVCSError`, skipping any unsupported VCSs.

**Comment by miki725** [comment]
can we close? fix was already merged
